<TABLE class=footer width="100%" border="0" cellspacing="0" cellpadding="2">
  <TR>
    <TD align="center"><SPAN class=footer>
      All trademarks and copyrights on this page are properties of their respective owners. <br>
      Last updated on 29-May-2002, 
      Copyright &copy; 1998-2002 by Jochen Hoenicke.
      Canonic URL is <a class=boldlink href="http://jode.sourceforge.net/">http://jode.sourceforge.net/</a></SPAN>
    </TD>
  </TR>
</TABLE>

</BODY>
</HTML>
